name: CI with Cache

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache Python dependencies and virtual environment
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: cache-c55a6c3

      # Prime cache step (prints hit/miss)
      - name: prime-cache-c55a6c3
        run: |
          if [ "${{ steps.cache-deps.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      # Step with your email address
      - name: 21f1002652@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions!"
